# Generated by Django 4.2.3 on 2023-07-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaveDinamica',
            fields=[
                ('cedula_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cuentas_app.cliente')),
                ('correo', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('num_cuenta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('estado', models.IntegerField(choices=[(0, 'Inactiva'), (1, 'Activa')])),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_apertura', models.DateField()),
                ('cedula_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='cuentas_app.cliente')),
            ],
        ),
    ]
